name: liquidmoniproject
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  mongo_dart: ^0.9.1
  http: ^0.13.5
  http_server: ^1.0.0
  mailer: ^6.0.1
  decimal: ^2.3.2
  twilio_dart_api: ^0.0.1
  swagger_dart_code_generator: ^2.11.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
